---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: autoservice
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: backend-t-academy:latest
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        env:
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)?sslmode=disable"
      initContainers:
        - name: migrations
          image: backend-t-academy:latest
          imagePullPolicy: IfNotPresent
          command: ["./app", "migrate"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          env:
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)?sslmode=disable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: autoservice
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: frontend-t-academy:latest
        imagePullPolicy: IfNotPresent
        name: frontend
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          valueFrom: 
            configMapKeyRef:
              name: app-config
              key: FRONTEND_PORT
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HTTP_PORT
        - name: BACKEND_URL
          value: "http://backend:$(API_PORT)"
        - name: COOKIE_SECURE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: COOKIE_SECURE
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: autoservice
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---