apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: autoservice
type: Opaque
stringData:
  POSTGRES_USER: "autoservice"
  POSTGRES_PASSWORD: "autoservice"
  JWT_SECRET: "change-me-change-me-change-me-change-me-0000"
  BOT_API_KEY: "change-me-bot-runner-api-key"
  BOT_TOKEN_ENCRYPTION_KEY: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
