---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: autoservice
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: autoservice
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: autoservice
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  selector:
    app: frontend
  type: NodePort
---